# Generated by Django 2.1.3 on 2019-02-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('number_of_customers', models.IntegerField(default=0)),
            ],
        ),
    ]
